import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="conteiner">
          {/* <div max-w-3x1 mx-auto px-5 md:max-w-2xl lg:max-w-4xl lg:px-10 xl:max-w-6xl> */}
            {children}
          {/* </div>   */}
        </div>
        {/* {children} */}
      </body>
    </html>
  );
}
